name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: packpilot-461918
  SERVICE_NAME: ecco-studio-web
  REGION: us-central1
  WIF_PROVIDER: projects/896693139975/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  WIF_SERVICE_ACCOUNT: github-actions-ecco-studio@packpilot-461918.iam.gserviceaccount.com

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 8080 \
            --min-instances 0 \
            --max-instances 10 \
            --cpu 1 \
            --memory 512Mi \
            --concurrency 80 \
            --quiet

      - name: Show Service URL
        run: |
          echo "Service deployed to:"
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format 'value(status.url)'
